# Generated by Django 3.1.3 on 2020-12-03 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_contactinfo1_studentinfo1_teacherinfo1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Parent2',
            fields=[
                ('parent1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testApp.parent1')),
                ('rollno', models.IntegerField()),
                ('marks', models.IntegerField()),
            ],
            bases=('testApp.parent1',),
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('parent2_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testApp.parent2')),
                ('subject', models.CharField(max_length=30)),
                ('salary', models.IntegerField()),
            ],
            bases=('testApp.parent2',),
        ),
    ]
